# register 3 users
# post 1 recipe to each user
# update recipe with correct author


### REGISTER Users
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username" : "alvian@gmail.com",
  "password" : "123456789",
  "role" : "ROLE_USER"
}
###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username" : "wanda@gmail.com",
  "password" : "123456789",
  "role" : "ROLE_USER"
}
###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username" : "yusuf@gmail.com",
  "password" : "123456789",
  "role" : "ROLE_USER"
}

### add 1 recipe to each user
POST http://localhost:8080/api/recipe/new
Content-Type: application/json
Authorization: Basic wanda@gmail.com 123456789

{
  "name": "bakso urat",
  "category": "bakso",
  "description": "Light, aromatic and refreshing beverage, ...",
  "ingredients": ["boiled water", "honey", "fresh mint leaves, add sambal"],
  "directions": ["Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"]
}

###
POST http://localhost:8080/api/recipe/new
Content-Type: application/json
Authorization: Basic yusuf@gmail.com 123456789

{
  "name": "bakso mercon",
  "category": "bakso",
  "description": "Light, aromatic and refreshing beverage, ...",
  "ingredients": ["boiled water", "honey", "fresh mint leaves, add sambal"],
  "directions": ["Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"]
}
###
POST http://localhost:8080/api/recipe/new
Content-Type: application/json
Authorization: Basic alvian@gmail.com 123456789

{
  "name": "bakso lava",
  "category": "bakso",
  "description": "Light, aromatic and refreshing beverage, ...",
  "ingredients": ["boiled water", "honey", "fresh mint leaves, add sambal"],
  "directions": ["Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"]
}

### UPDATE recipe according to its author
PUT http://localhost:8080/api/recipe/1
Content-Type: application/json
Authorization: Basic wanda@gmail.com 123456789

{
  "name": "update - bakso urat",
  "category": "update - bakso",
  "description": "update - Light, aromatic and refreshing beverage, ...",
  "ingredients": ["update - boiled water", "honey", "fresh mint leaves, add sambal"],
  "directions": ["update - Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"]
}

> {%
    client.test("no content", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}
###
PUT http://localhost:8080/api/recipe/2
Content-Type: application/json
Authorization: Basic yusuf@gmail.com 123456789

{
  "name": "update - bakso mercon",
  "category": "update - bakso",
  "description": "update - Light, aromatic and refreshing beverage, ...",
  "ingredients": ["update - boiled water", "honey", "fresh mint leaves, add sambal"],
  "directions": ["update - Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"]
}

> {%
    client.test("no content", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}
###
PUT http://localhost:8080/api/recipe/3
Content-Type: application/json
Authorization: Basic alvian@gmail.com 123456789

{
  "name": "update - bakso lava",
  "category": "update - bakso",
  "description": "update - Light, aromatic and refreshing beverage, ...",
  "ingredients": ["update - boiled water", "honey", "fresh mint leaves, add sambal"],
  "directions": ["update - Boil water", "Pour boiling hot water into a mug", "Add fresh mint leaves", "Mix and let the mint leaves seep for 3-5 minutes", "Add honey and mix again"]
}

> {%
    client.test("no content", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}
